name: PR generator


on:
  push:
    branches-ignore: master

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.TOKEN }}
          title: Automatic pull request
          source_branch: origin/develop
          target_branch: origin/qa